### ISSUE TITLE
Mcm preset missing 

### ISSUE THREAD

**Issue by DILLOY** [NomadsReach/Fallout-Anomaly#10]
Please use the below as a template when making your report.

## Describe the bug

When I was first installing 4.9 from wabba I was following the github start up directions and noticed that the mcm preset was not present.

### Is it already a known issue?

Yes

### Steps to reproduce
Steps to reproduce the behavior.

N/A

### Environment
 
- OS: Windows 11

   
### Contact

MrDILLOY

**Comment by NomadsReach** [comment]
Issue is not a bug and is in the work.
