### ISSUE TITLE
Darlene House Freeze

### ISSUE THREAD

**Issue by coc568** [NomadsReach/Fallout-Anomaly#106]
- Please include a way to contact you. Discord Name w/ # etc.
  Sharky128

- Brief description of the issue.
  complete game freeze, no crash logs

- Steps to reproduce the issue or details of what happened. Please also include computer hardware.
  In Darlene's house in Lexington, room 303. if you go all the way down the hall to the bathroom. If you use the "autodoc" the game will take a sec and it'll run a scan and then do the healing. once its done the healing itll pull up a screen saying fully healed or whatever its programed to say, and once you hit okay to go out of the screen the game freezes. i have attempted to repeat this 5+ times. It has happened each time, i wanted to make sure it was not a freak accident before i reported it.

**Comment by NomadsReach** [comment]
@ZatosTTV @coc568 Can one of please try to reproduce this on current 0.4.9 version.
