### ISSUE TITLE
Alternate Currencys idea

### ISSUE THREAD

**Issue by DILLOY** [NomadsReach/Fallout-Anomaly#11]
### Summary

This mod adds various currencys like rubles, usd, euro,  

### Basic example
 
https://www.nexusmods.com/fallout4/mods/76903

Having traders cross map that would b3 dealers/traders and they buy snd sell in different currencys in some places, maybe even a black market kinda deal or just in general use money instead of caps I think yous could do some cool custom things with this mod! :) 

### MOTIVATION
 
My motive it to extend the currency system to implament different currencys to more further expand on the stalker like vibe yous are going for!

**Comment by NomadsReach** [comment]
Thank you for the ideas. We will look at adding them in the future. 

There is a currency mod in place now that uses military ammo instead of caps.

https://www.nexusmods.com/fallout4/mods/57854
