### ISSUE TITLE
Consider using Pilgrim Definitive Edition - ENB and Weather

### ISSUE THREAD

**Issue by Cube-13** [NomadsReach/Fallout-Anomaly#12]
## Summary
Since you guys are going for the S.T.A.L.K.E.R. look, you might think about using Pilgrim.

### Basic example
[Pilgrim Definitive Edition - ENB and Weather](https://www.nexusmods.com/fallout4/mods/75773).  Adds spooky/dreadful looking atmospherics, including creepy music and sounds.  Unfortunately the mod author claims it can't be used with other Weather mods.

### Motivation
To me this would greatly support and enhance your decision to go for a S.T.A.L.K.E.R. type vibe.  I used the original version of Pilgrim a few years ago and it really does change your perception of the game to a dark and dreary commonwealth.  I have a feeling though that a patch can be made for various weather mods through xEdit.

**Comment by NomadsReach** [comment]
Thank you, I forgot all about Pilgrim. I will look into this for the next update!
