### ISSUE TITLE
AR2 Issue with quest

### ISSUE THREAD

**Issue by ZatosTTV** [NomadsReach/Fallout-Anomaly#126]
Doing the American Rising part 2 modded quest line. Quest name is "Humanity Must Shape Their Tools".
The book I'm getting is when Captain Peterson shows up with two guys and X01 power armor one is meant to blow down the door but after he says "fire in a hole" nothing happens.

**Comment by NomadsReach** [comment]
Need to check for conflicts regarding this and also see about pushing a updated version of this mod to 0.4.9.
