### ISSUE TITLE
Random CTD

### ISSUE THREAD

**Issue by Stationdown** [NomadsReach/Fallout-Anomaly#13]
Here is my crash log. It just happens randomly, hopefully its an easy fix.

https://pastebin.com/LiztCJH5

**Comment by NomadsReach** [comment]
====================================================
SCANNING THE LOG FOR SPECIFIC (POSSIBLE) SUSPECTS...
====================================================
# LIST OF (POSSIBLE) PLUGIN SUSPECTS #
* COULDN'T FIND ANY PLUGIN SUSPECTS *

# LIST OF (POSSIBLE) FORM ID SUSPECTS #
- Form ID: 0002B785 | [Fallout4.esm] | 19
- Form ID: 000A1AD2 | [Fallout4.esm] | 2
- Form ID: 001231B2 | [Fallout4.esm] | 2
- Form ID: 0018DEB3 | [Fallout4.esm] | 9
- Form ID: 0018DEDF | [Fallout4.esm] | 2

[Last number counts how many times each Form ID shows up in the crash log.]
These Form IDs were caught by Buffout 4 and some of them might be related to this crash.
You can try searching any listed Form IDs in xEdit and see if they lead to relevant records.

# LIST OF DETECTED (NAMED) RECORDS #
- (char*) "Effects\Ambient\MistLowSlow.nif" | 3
- (char*) "SetDressing\CanvasPainting01.BGSM" | 1
- (char*) "setdressing\paintingsgeneric\PaintingGeneric_CanvasSwap.BGSM" | 2
- Name: "BldWoodPSmRailStairsShort01RDest" | 7
- Name: "BldWoodPSmRailStairsShort01RDest:11" | 3
- Name: "DestNode:3" | 1
- Name: "FemaleMannequinBurnt01" | 1
- Name: "FootFXDirtSmall" | 2
- Name: "Materials\SetDressing\PaintingsGeneric\PaintingGeneric_CanvasSwap.BGSM" | 1
- Name: "MistLowSlow" | 11




**Where in game did thsi crash happen?** @Stationdown

**Comment by NomadsReach** [comment]
Being investigated...

**Comment by NomadsReach** [comment]
@Stationdown i think I found a fix. Can you reach out to me on discord

**Comment by NomadsReach** [comment]
![image](https://github.com/NomadsReach/Fallout-Anomaly/assets/144523850/d9665a31-2f43-4f05-a31a-f09a42d0f158)

Here is the fix!
