### ISSUE TITLE
Settlement addons

### ISSUE THREAD

**Issue by KHorvinus** [NomadsReach/Fallout-Anomaly#15]
## Summary
I was wondering if possible to add more SS2 addon packs and possibly some settlement mods that can help build or add items to workshop

### Basic example
Examples i guess for SS2 addons would be Pra's or some of the other city building plans. Examples of settlement mods include CvC wasteland etc.

### Motivation

Settlements are necessary for immersion and survival it adds to making the game feel lived in or your own. It is something people can do if they want or just ignore that aspect. Also I just like making settlements or enhancing Sim Settlements.

**Comment by NomadsReach** [comment]
These will be added at the end of 0.4.9 and some which you referenced are being planned to be put in.

**Comment by KHorvinus** [comment]
Overall it depends on the aesthetic you want to maintain. Is this a ruined
world where is pieced together from the old world or some areas that are
rebuilt from hard work to look like it did prewar. I say this because there
are all kinds of packs and since we have modern weapons in-game such as
SP12. I think it would be easy to incorporate any SS2 addon packs or
settlement packs, they are esl and sit in the SS2 folder as is. I can drum
up someones when you let me know the direction of look you guys want to
maintain.

**Comment by KHorvinus** [comment]
So far I have added Rise of the Commonweath and CvC wasteland without issues other than CVC needing to be treated for survival. I am going to add some more SS2 plot packs, but have not been able to get any others settlement presets to work.
