### ISSUE TITLE
Overlapping issue

### ISSUE THREAD

**Issue by Keldargames** [NomadsReach/Fallout-Anomaly#16]
Please use the below as a template when making your report.

## Describe the bug
Overlapping MOdStarts right after the Vault

### Is it already a known issue?
No

### Steps to reproduce
happens every time i start a new game

### Environment
 - OS: Win10
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
    
   Please list your discord name if you are in our discord:
Keldar

---

### Additional context
This happened with the latest update as far as i know, 19:55 CET, wabbajack overwrite install. New Game ofc. 
You can work aroung with keyboard, then use the mouse for the TAG Skills.
https://youtu.be/p-tiKPkTM7Y

---

**Comment by NomadsReach** [comment]
Thank you, It's known at the moment. I can't fix it at this time, but click the option in the background as you did.
