### ISSUE TITLE
Terrible Pip Boy Menu

### ISSUE THREAD

**Issue by Keldargames** [NomadsReach/Fallout-Anomaly#17]
Please use the below as a template when making your report.

## Describe the bug
Pip Boy Menu is pretty hard to read. Is there a MCM Setting i haven't found yet for the pip boy?

### Steps to reproduce
Every time i open the pip boy

### Environment
 - OS: Win10
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
    
   Please list your discord name if you are in our discord:

Keldar
---

### Additional context
https://youtu.be/C-jw_191il8

---

**Comment by NomadsReach** [comment]
Open console and type FOV 80-110 whicher you like the most and then type refreshini and save. :)
