### ISSUE TITLE
Random Crashes 

### ISSUE THREAD

**Issue by LordErika67** [NomadsReach/Fallout-Anomaly#18]
Please use the below as a template when making your report.

## Describe the bug
Random crash for some unknow reason , sometimes when doing absolutely nothing sometime when fighting 

### Is it already a known issue?
no.
### Steps to reproduce
Steps to reproduce the behavior.

### Environment
 - OS: [e.g. Arch Linux]
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
    
Dziobak#8426

---

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from discord.

---
[crash-2024-02-16-06-14-03.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14353624/crash-2024-02-16-06-14-03.log)

**Comment by NomadsReach** [comment]
SCANNING THE LOG FOR SPECIFIC (POSSIBLE) SUSPECTS...
====================================================
# LIST OF (POSSIBLE) PLUGIN SUSPECTS #
- MAIM 2.esp | 8

[Last number counts how many times each Plugin Suspect shows up in the crash log.]
These Plugins were caught by Buffout 4 and some of them might be responsible for this crash.
You can try disabling these plugins and check if the game still crashes, though this method can be unreliable.

# LIST OF (POSSIBLE) FORM ID SUSPECTS #
- Form ID: 00000007 | [Fallout4.esm] | 15
- Form ID: 00000014 | [Fallout4.esm] | 15

[Last number counts how many times each Form ID shows up in the crash log.]
These Form IDs were caught by Buffout 4 and some of them might be related to this crash.
You can try searching any listed Form IDs in xEdit and see if they lead to relevant records.

# LIST OF DETECTED (NAMED) RECORDS #
- Full Name: "- Fractured Left Arm" | 6
- Name: "WoodFirePot" | 1
- Name: "b_Sway" | 1

**Comment by NomadsReach** [comment]
I will look through and try to reproduce this issue. Did you start on a new save as of the most recent updated?

**Comment by NomadsReach** [comment]
![image](https://github.com/NomadsReach/Fallout-Anomaly/assets/144523850/bddda473-95f3-4cf0-822a-b53cb4132c2d)

Here is the fix @LordErika67 would love for you to join back.
