### ISSUE TITLE
Animation issue.

### ISSUE THREAD

**Issue by JustBaron1** [NomadsReach/Fallout-Anomaly#19]
## Describe the bug
Unarmed crouch animation on female character (haven't checked male).

### Is it already a known issue?
No

### Steps to reproduce
Holster weapon, go in 3rd person and crouch/stand up.
   

### Contact: 
    
just_baron

---

### Additional context
Unarmed character starts crouching in vanilla animation, then twitches and stands in cautious crouch animation, and moves with the same speed as running (not sprinting on "shift", just a regular speed) one.
---

**Comment by NomadsReach** [comment]
Please update to the newest patch. I have not been able to reproduce this issue.
