### ISSUE TITLE
CTD entering into museum 

### ISSUE THREAD

**Issue by r3mot3control** [NomadsReach/Fallout-Anomaly#22]
[crash-2024-02-22-00-10-38.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14366719/crash-2024-02-22-00-10-38.log)
[crash-2024-02-22-00-10-38-AUTOSCAN.md](https://github.com/NomadsReach/Fallout-Anomaly/files/14366720/crash-2024-02-22-00-10-38-AUTOSCAN.md)
[crash-2024-02-22-00-59-04.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14366721/crash-2024-02-22-00-59-04.log)
[crash-2024-02-22-00-59-04-AUTOSCAN.md](https://github.com/NomadsReach/Fallout-Anomaly/files/14366722/crash-2024-02-22-00-59-04-AUTOSCAN.md)
Please use the below as a template when making your report.

## Describe the bug
CTD

windows 11
 
 AMD Ryzen 7 5700X 8-Core Processor   3.40 GHz
 32.0 GB (31.9 GB usable)
 Nvidia Geforce RTX 3060ti
   

### Contact: 
new r3mot3control

**Comment by NomadsReach** [comment]
@r3mot3control  One of your crash was due to the fix in #📜known-issues 

For the other issue at some point your game is saving and crashing upon that point. 

You have updated with overwrite install and as of 2/20/2024 a new save is required. At what point did you start this character?

**Comment by r3mot3control** [comment]
I started one today modlist seems to be up to date as there isn't an indication to download a new one. its running pretty good now. the odd crash usually while sitting still for a period of time.

**Comment by NomadsReach** [comment]
Thank you, if the issue comes up again please open a new ticket.
