### ISSUE TITLE
Crash on launch. "EXCEPTION_ACCESS_VIOLATION" at 0x7FFBB135ECA0 d3d11.dll+012ECA0

### ISSUE THREAD

**Issue by ElisPlayz** [NomadsReach/Fallout-Anomaly#23]
## Describe the bug
Whenever the game is launched, after the ENB loads, it calls "EXCEPTION_ACCESS_VIOLATION" at 0x7FFBB135ECA0 d3d11.dll+012ECA0

This crash is repetetive, every time I launch the game, same thing happens.

### Is it already a known issue?
Not that I believe so, no. 

### Steps to reproduce
1) Launch the game through MO2;
2) Try clicking something in-game post ENB loading.

### Environment
// From crashlog:
	OS: Microsoft Windows 10 Pro v10.0.19044
	CPU: AuthenticAMD AMD Ryzen 5 3600 6-Core Processor              
	GPU #1: Nvidia TU104 [GeForce RTX 2060]
	GPU #2: Microsoft Basic Render Driver
	PHYSICAL MEMORY: 13.14 GB/31.94 GB
   

### Contact: 
I am not in your discord server due to server limit on my main. Incase you wish to contact me, copy and paste this exact name: mrlei

---

### Additional context
I'll attach the crashlog, as for the CLAS, the one bundled with the MO2 crashes on launch.

Here's the crashlog:
https://pastebin.com/DNW704fW

---

**Comment by NomadsReach** [comment]
@ElisPlayz 

Please verify you have all the pre-install requirements listed in the read me. 

Please also add the MO2.exe and Fallout4.exe as an exception in your antivirus. The Fallout4.exe will be in the MO2 folder within the Stock folder.

more info can be found here: https://docs.google.com/document/d/17FzeIMJ256xE85XdjoPvv_Zi3C5uHeSTQh6wOZugs4c/edit

**Comment by ElisPlayz** [comment]
After reinstalling everything from the pre-install requirements list, Buffout started to point out one specific .dds that calls CreateTexture2D fails with. Here's the full error: https://imgur.com/a/1bW9zHK
