### ISSUE TITLE
Vanishing And Reappearing objects {DO NOT CLOSE}

### ISSUE THREAD

**Issue by DILLOY** [NomadsReach/Fallout-Anomaly#25]
Please use the below as a template when making your report.

## Describe the bug

--- MrDILLOY: I started a fresh new game on the latest fallout anomaly build and was clearing out all items from Concord when I came across the loot trunk in the Concord Speakeasy that had a vanishing issue when I got close it vanished and far it reappears.

### Is it already a known issue?
If so or you are not sure please do not make a new request and see the known issue page.

--- MrDILLOY: I am not sure but i have checked the Know issues to see fi someone has reported it. 

### Steps to reproduce
Steps to reproduce the behavior.

--- MrDILLOY: To be honest, I just came across it not sure if it reoccurs on other builds of fallout anomaly. 

### Environment

MrDILLOY's PC Specs 
--- Windows 11 Home
      32.0 GB Ram 
      Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
      64-bit operating system
      Nvidia Geforce RTX 2060 6gb vram

### Contact: 
    
   Please list your discord name if you are in our discord: 

--- MrDILLOY

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from Discord.

--- Keep this open nomad I will post more in the same channel if I come across any vanishing issues.  

![Screenshot (129)](https://github.com/NomadsReach/Fallout-Anomaly/assets/115899212/0a2f1409-1230-42ac-9dbb-7619477456cd)

**Comment by NomadsReach** [comment]
Thank you
