### ISSUE TITLE
Concord Museum {NON} Recurring Crash 

### ISSUE THREAD

**Issue by DILLOY** [NomadsReach/Fallout-Anomaly#26]
Please use the below as a template when making your report.

## Describe the bug

--- MrDILLOY: from the speakeasy in Concord to the top of the sim settlements Jake's sleeping area and slept in his bed then to the museum that's when the crash occurred.

### Is it already a known issue?
If so or you are not sure please do not make a new request and see the known issue page.

--- MrDILLOY: just a one-off crash probably to do with Nvidia graphics, idk if they may have fixed that issue with Nividia GPUS and Fallout 4.

### Steps to reproduce
Steps to reproduce the behavior.

--- MrDILLOY: from testing it is not a reoccurring crash.

### Environment

MrDILLOY's PC Specs 
--- Windows 11 Home
      32.0 GB Ram 
      Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz   3.60 GHz
      64-bit operating system
      Nvidia Geforce RTX 2060 6gb vram

### Contact: 
    
   Please list your discord name if you are in our discord: 

--- MrDILLOY

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from Discord.

--- [crash-2024-02-22-21-02-09.log.txt](https://github.com/NomadsReach/Fallout-Anomaly/files/14379378/crash-2024-02-22-21-02-09.log.txt)

**Comment by DILLOY** [comment]
[musemum crashlog 2.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14379566/musemum.crashlog.2.log)

I got this one after clearing the Concord of Raiders and then going to the museum.

**Comment by NomadsReach** [comment]
Thank you for the really informative report and being detailed. I will review these and see what I come up with. 🙂

**Comment by Starkmens** [comment]
I also just received this crash again. Just cleared Concord and went into the museum for the first time.
[crash-2024-02-24-20-43-25.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14394409/crash-2024-02-24-20-43-25.log)

Discord: Starkmens

**Comment by NomadsReach** [comment]
Trying to find the reason behind this but sadly the crash logs are not very helpful. I have pushed a new update again just now to hopefully further prevent this.

**Comment by Atlas510** [comment]
Crash when entering museum.

[crash-2024-02-26-07-05-30.log.txt](https://github.com/NomadsReach/Fallout-Anomaly/files/14400920/crash-2024-02-26-07-05-30.log.txt)

Discord: Atlas

**Comment by NomadsReach** [comment]
Has this occured on the newest compile?

**Comment by NomadsReach** [comment]
Seems to finally be fixed in the new update.
