### ISSUE TITLE
Crashing Upon Startup

### ISSUE THREAD

**Issue by ZenitharAmbi** [NomadsReach/Fallout-Anomaly#27]
Please use the below as a template when making your report.

## Describe the bug
Game crashes upon text for ENB information appearing in the top left

### Is it already a known issue?
It is not listed in the known issues tab.

### Steps to reproduce
Launching from Anomaly Launcher or F4SE on the latest version.

### Environment
 - OS: Windows 11 latest update as of 2/23/2024
 - Nvidia RTX 3060ti, AMD R5 5600 6 Cores, 32gb DDR4 ram 3200mhz
 - Other details that you think may affect.
   

### Contact: 
    
   Discord username is memeusbulis/ambiguzen

---

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from discord.

---
[crash-2024-02-23-20-31-27.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14390219/crash-2024-02-23-20-31-27.log)

**Comment by NomadsReach** [comment]
Fixed in the new compile as of today.
