### ISSUE TITLE
Two issues i found today

### ISSUE THREAD

**Issue by KHorvinus** [NomadsReach/Fallout-Anomaly#29]
Please use the below as a template when making your report.

## Describe the bug
The SPAS-12 shotgun is invisible, the binoculars when used stay in the hud of the binoculars and you can only fix by reloading a previous save.

### Is it already a known issue?
Not that I have seen?

### Steps to reproduce
Equip then watch...oh no....

### Environment
 -Rad storm, summer, local pub you name it
   

### Contact: 
    
   Please list your discord name if you are in our discord:

---

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from discord.

---

**Comment by NomadsReach** [comment]
![image](https://github.com/NomadsReach/Fallout-Anomaly/assets/144523850/e11e147e-5825-48e8-aa17-0d3c6213a778)


Hey there, I haven't been able to reproduce the spas12 issue but I do know it can happen. Can you get a picture of it in your inventory. 

The binocular issue I confirmed and will have a fix out for it sometime today.

**Comment by KHorvinus** [comment]
Ok i will have to take another picture, i already deleted it. i will try reinstalling it first.  Also now Sim Settlements is not showing built plots. I tried refreshing and even a new start up. I had previously downloaded Rise of the commonwealth and a sanctuary plan and thought that was the problem, but the latest wabbajack update let it visually not showing. I will try reloading that as well. 

![Photo3](https://github.com/NomadsReach/Fallout-Anomaly/assets/160057682/cdffb835-f4f2-4971-af27-c8bfb7e31d20)

**Comment by NomadsReach** [comment]
Binoculars have been fixed.
