### ISSUE TITLE
Add the SA58 FAL mod to the modpack

### ISSUE THREAD

**Issue by sovietpolarbear** [NomadsReach/Fallout-Anomaly#30]
## Summary
The SA58 FAL mod allows up to 9 different variations of the FAL from coldwar to modern-Anomaly Tarkov era FALs.

### Basic example
https://www.nexusmods.com/fallout4/mods/40907

### Motivation
I've been playing with mods in Bethesda games for more than a decade and this mod itself is one of the highest quality gun mods I've ever seen in a game. Although the mod does come with some weird immersion breaking locations, it can easily be fixed with this mod

https://www.nexusmods.com/fallout4/mods/49717?tab=files

**Comment by NomadsReach** [comment]
Thank you, I will look into it! Awesome motivation.
