### ISSUE TITLE
Crash on loading screen. Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FF694033CCD Fallout4.exe+0053CCD

### ISSUE THREAD

**Issue by Atlas510** [NomadsReach/Fallout-Anomaly#31]
I selected continue game. The game entered the standard loading screen attempting to load into my save, then the game crashed. 
   
[crash-2024-02-25-12-52-23.log.txt](https://github.com/NomadsReach/Fallout-Anomaly/files/14396403/crash-2024-02-25-12-52-23.log.txt)

Discord Name:
Atlas

**Comment by NomadsReach** [comment]
Are you still having this issue? Have you tried seeing if a new save loads for testing purposes? @Atlas510
