### ISSUE TITLE
Tyre and floor texture bug 

### ISSUE THREAD

**Issue by Spookyboi34** [NomadsReach/Fallout-Anomaly#34]
Please use the below as a template when making your report.

The textures on tyres and certain junk piles are missing or bugged, they appear to not fit on the actual object. They have a weird 3d effect when you move while looking at them

Go to Red Rocket Truck Stop and look at the tires.
   
My discord name is Spookyboi.

Unsure if this is a problem with this list in particular, seen similar issues before. Screenshots attached

![Photo1](https://github.com/NomadsReach/Fallout-Anomaly/assets/22487981/e3451b37-4442-4e8a-9ef5-8a59fb1dc4f9)
![Photo2](https://github.com/NomadsReach/Fallout-Anomaly/assets/22487981/1a6a1d5a-6544-4661-863e-01dacf84e085)
![Photo3](https://github.com/NomadsReach/Fallout-Anomaly/assets/22487981/8f79b94b-1a2e-46c8-9ed2-552bb14e3e3e)
![Photo4](https://github.com/NomadsReach/Fallout-Anomaly/assets/22487981/81223cfe-b8a5-414a-b6cb-ffb32b3dc80a)
![Photo5](https://github.com/NomadsReach/Fallout-Anomaly/assets/22487981/3323fdec-7ed9-409f-9427-bdd1f0ffa5cc)
![Photo6](https://github.com/NomadsReach/Fallout-Anomaly/assets/22487981/09c8e3ef-a20a-4bf8-b07c-ec69dd368f45)
![Photo7](https://github.com/NomadsReach/Fallout-Anomaly/assets/22487981/ca0c8310-d42b-4925-9118-02d25942c1d1)
![Photo8](https://github.com/NomadsReach/Fallout-Anomaly/assets/22487981/666b5d94-8aab-42b2-8b5c-20b2efb2d739)
![Photo0](https://github.com/NomadsReach/Fallout-Anomaly/assets/22487981/5ac23bcf-db68-48a6-a601-486bfa6e1679)

**Comment by NomadsReach** [comment]
Yeah, I’ve seen this in other mods as well. I’ll have a look at what is changing it.

**Comment by NomadsReach** [comment]
This issue can be fixed by disabling parallax in the ENB. I'll look into this more for the next update.
