### ISSUE TITLE
Bullet Counted Reload Patch for Hunting Shotgun

### ISSUE THREAD

**Issue by Spookyboi34** [NomadsReach/Fallout-Anomaly#35]
Not sure if this is a bug fix request or a feature request, but BCR doesn't work for the hunting shotgun, looks like there are a few patches for this on the Nexus to fix this. 

https://www.nexusmods.com/fallout4/mods/41339

Also, might be worth excluding this shotgun from Bullet in the Chamber so it doesn't drop the shells.

**Comment by NomadsReach** [comment]
Issue resolved in upcoming patch. Please report any further issues.
