### ISSUE TITLE
Backpack disappearing

### ISSUE THREAD

**Issue by Starkmens** [NomadsReach/Fallout-Anomaly#36]
Please use the below as a template when making your report.

## Describe the bug
Backpack just disappears out of my inventory. Happened three times now. Not sure if I did it every time but last two times I noticed after loading from a save.

### Steps to reproduce
I have loaded previous saves to see if it is there and it did not show up on any of them.

### Environment
 - OS: Win11
 - Intel Arc: A770
 - I7
   

### Contact: 
    
Discord: Starkmens

---

### Additional context
Happened on a previous patch but I didn't pay attention to much cause a new patch came out soon after. I am pretty sure it disappeared after I died and loaded back in.

---

**Comment by NomadsReach** [comment]
Can you get me the names of the backpacks or what mod they are from? Dropping them on the ground and clicking on them in console should get that for you.

**Comment by NomadsReach** [comment]
https://www.nexusmods.com/fallout4/mods/58032?tab=bugs


This issue is reported on the bugs section for the backpack mod
