### ISSUE TITLE
MoF Crashing

### ISSUE THREAD

**Issue by ZenitharAmbi** [NomadsReach/Fallout-Anomaly#37]
Please use the below as a template when making your report.

## Describe the bug
Game Crashes at the Museum Of Freedom when entering

### Is it already a known issue?
It is not listed in the Known Issues section
### Steps to reproduce
Enter Museum of Freedom
### Environment
 Windows 11 latest update, 3060ti, 32GB DDR4 RAM at 3200mhz, Ryzen 5 5600
   

### Contact: 
    
Discord name: Ambiguzem

---

### Additional context
crash log and scanned crash log provided.

---

[crash-2024-02-26-15-15-16.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14406648/crash-2024-02-26-15-15-16.log)
[crash-2024-02-26-15-15-16-AUTOSCAN.md](https://github.com/NomadsReach/Fallout-Anomaly/files/14406651/crash-2024-02-26-15-15-16-AUTOSCAN.md)

**Comment by NomadsReach** [comment]
Can you please if you have this issue again post it in https://github.com/NomadsReach/Fallout-Anomaly/issues/26


This is the main log for the concord museum issue.
