### ISSUE TITLE
Blackface Bug

### ISSUE THREAD

**Issue by Keldargames** [NomadsReach/Fallout-Anomaly#4]
Please use the below as a template when making your report.

## Describe the bug
Blackfaces of NPC's

### Is it already a known issue?
Kind of known, happens randomly.

### Steps to reproduce
Not persistent. Reloading sometimes fixes the bug, randomly appears again.

### Environment
 - OS: Win10
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
    
Keldar

---

### Additional context

https://youtu.be/pmaUDqZVGVg
---

**Comment by NomadsReach** [comment]
https://www.nexusmods.com/fallout4/articles/4121/

Very common issue that is hit and miss on trying to fix. 

Ongoing progress to resolve...
