### ISSUE TITLE
Weapon suggestion

### ISSUE THREAD

**Issue by KHorvinus** [NomadsReach/Fallout-Anomaly#43]
Some SMGS!

### Basic example
MP5, etc.

### Motivation
Because SMGs are fun to play with

**Comment by KHorvinus** [comment]
Also there is is great ak mod on Vault Omega discord. He does a Escape from Tarkov modlist. The TUK AK mod he translated it from a Russian modder. if interested I can make a link.

**Comment by NomadsReach** [comment]
https://github.com/NomadsReach/Fallout-Anomaly/issues/46 can you use this for weapon suggestions, thank you!
