### ISSUE TITLE
Energy Weapons

### ISSUE THREAD

**Issue by FridayNightToon** [NomadsReach/Fallout-Anomaly#44]
## Summary
The Stalker side of the current weapon list is pretty good, but there's a severe lack of energy weapon variety both in the base game and the as of now modlist, so more options to better flesh out the Fallout side of the weapon roster would be really nice.

### Basic example
https://www.nexusmods.com/fallout4/mods/53998
https://www.nexusmods.com/fallout4/mods/61875
https://www.nexusmods.com/fallout4/mods/27050

**Comment by NomadsReach** [comment]
https://github.com/NomadsReach/Fallout-Anomaly/issues/46 can you use this for weapon suggestions, thank you!
