### ISSUE TITLE
Post your WEAPON SUGGESTIONS here!

### ISSUE THREAD

**Issue by Spookyboi34** [NomadsReach/Fallout-Anomaly#46]
## Summary
Weapon Suggestions :) 

### Basic example

Mosin would be cool af:
https://www.nexusmods.com/fallout4/mods/23258

SVT-40 is cool as well (or any of this guys mods, he makes cool lorefriendlyish weapons. I think I saw you had his bundle of tape pack in the past):
https://www.nexusmods.com/fallout4/mods/22017/?

The AK5C, has some goofy attachments, but a cool weapon with heaps of customization. 
https://www.nexusmods.com/fallout4/mods/28418

The Grease Gun is very cool, especially for early in the game:
https://www.nexusmods.com/fallout4/mods/21921

Micalov's Institute Tech Overhaul is sick too, but would probably be a huge pain to get added.
https://www.nexusmods.com/fallout4/mods/70352

Thanks Team for all the work you do :)

**Comment by NomadsReach** [comment]
https://www.nexusmods.com/fallout4/mods/48433

https://www.nexusmods.com/fallout4/mods/28418

The Stalker side of the current weapon list is pretty good, but there's a severe lack of energy weapon variety both in the base game and the as of now modlist, so more options to better flesh out the Fallout side of the weapon roster would be really nice.

Basic example
https://www.nexusmods.com/fallout4/mods/53998
https://www.nexusmods.com/fallout4/mods/61875
https://www.nexusmods.com/fallout4/mods/27050

**Comment by NomadsReach** [comment]
Use this page for weapon suggestions, thank you everyone.
