### ISSUE TITLE
Olivia flickering

### ISSUE THREAD

**Issue by Keldargames** [NomadsReach/Fallout-Anomaly#5]
Please use the below as a template when making your report.

## Describe the bug
Graphics flicker in and out inside Olivia

### Is it already a known issue?
Same bug happened in old 0.4.7

### Steps to reproduce
Seems to happen every time i enter Olivia

### Environment
 - OS: Win10
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
    
   Please list your discord name if you are in our discord:
Keldar

---

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from discord.
https://youtu.be/4jhQfA0cyHM
---

**Comment by NomadsReach** [comment]
Fixed in upcoming patch.
