### ISSUE TITLE
Pip-Boy W.S.

### ISSUE THREAD

**Issue by PatrickJnr** [NomadsReach/Fallout-Anomaly#51]
## Summary
Pip-Boy W.S. is my main favorite Pip-Boy mod.

### Basic example
https://www.nexusmods.com/fallout4/mods/76401

https://www.nexusmods.com/fallout4/mods/76543

### Motivation
Because it looks nice.

**Comment by NomadsReach** [comment]
For the time being we will keep using the pip-pad but I will look into adding the W.S as optional content.
