### ISSUE TITLE
Traffic Cone Visual Bug

### ISSUE THREAD

**Issue by Spookyboi34** [NomadsReach/Fallout-Anomaly#53]
Please use the below as a template when making your report.

## Describe the bug
Traffic cones appear to glow in the dark or have a blue filter over them. 

### Is it already a known issue?
Don't believe so

### Steps to reproduce
Spawn in game, look at traffic cone (only really obvious at night)

### Contact: 
    
Please list your discord name if you are in our discord: spookyboi

Screenshot attached.
![cones](https://github.com/NomadsReach/Fallout-Anomaly/assets/22487981/36785bbc-7d00-4fc1-8bb2-3c0b4c03a736)

**Comment by NomadsReach** [comment]
It will be fixed in next patch. It's from https://www.nexusmods.com/fallout4/mods/70447 and is a texture conflict with another texture mod.
