### ISSUE TITLE
Starlight Drive-In - Radiation Bug(?)

### ISSUE THREAD

**Issue by Spookyboi34** [NomadsReach/Fallout-Anomaly#54]
Please use the below as a template when making your report.

## Describe the bug
In Vanilla, removing the radiation barrels from Starlight Drive-In removes the rads from standing near the water in the middle. In Anomaly, this doesn't seem to remove the rads. Not 100% sure this is a bug, could be intentional but thought I'd raise it regardless. 

### Is it already a known issue?
Not that I can see.

### Steps to reproduce
Unlock Starlight Drive-In as a settlement, scrap all the radiation barrels (and cars to be safe), and stand near the water. You should still be getting irradiated. 

### Environment
Playing on the most recent dev build

### Contact:  
Please list your discord name if you are in our discord: spookyboi

**Comment by NomadsReach** [comment]
More than likely from https://www.nexusmods.com/fallout4/mods/37051.

Looking at it realistically, having radioactive waste sitting in water for that long means that simply removing those barrels wouldn't magically make the radioactive particles disappear. However, I will look into that further to see if this is in fact a bug.
