### ISSUE TITLE
crash logs

### ISSUE THREAD

**Issue by PikiSithLord** [NomadsReach/Fallout-Anomaly#55]
[crash-2024-03-09-23-03-26.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14548328/crash-2024-03-09-23-03-26.log)

[new crash.txt](https://github.com/NomadsReach/Fallout-Anomaly/files/14548329/new.crash.txt)

**Comment by NomadsReach** [comment]
[crash-2024-03-09-23-03-26-AUTOSCAN.md](https://github.com/NomadsReach/Fallout-Anomaly/files/14548645/crash-2024-03-09-23-03-26-AUTOSCAN.md)


Upload your save please and give a run down of what you were doing in game.
