### ISSUE TITLE
another crash

### ISSUE THREAD

**Issue by PikiSithLord** [NomadsReach/Fallout-Anomaly#56]
[yet another new crash.txt](https://github.com/NomadsReach/Fallout-Anomaly/files/14548507/yet.another.new.crash.txt)

**Comment by NomadsReach** [comment]
[crash-sith-AUTOSCAN.md](https://github.com/NomadsReach/Fallout-Anomaly/files/14548638/crash-sith-AUTOSCAN.md)

I need more info. Where did this happen, what were you doing, etc. Upload your save as well please.
