### ISSUE TITLE
cant seem to exit out of holotapes like cheat terminal.

### ISSUE THREAD

**Issue by x30inches** [NomadsReach/Fallout-Anomaly#57]
## cannot exit from holotapes.
when i try to open cheat terminal or any other holotape, i cant seem to exit. pressing tab does nothing. i am fresh out of the vault and have walked to red rocket and that is it. so far everything is functioning.

hardware: rtx 3060
i9 11900k 
64gb ddr4 
   

### Contact: 
    
x30inchesofdoom

**Comment by trister1000** [comment]
encountered this as well

**Comment by NomadsReach** [comment]
Has already been fixed in dev build and has been posted multiple times in the discord and nexus how to fix on current build.
