### ISSUE TITLE
Crashlog - Most recent build 

### ISSUE THREAD

**Issue by Spookyboi34** [NomadsReach/Fallout-Anomaly#58]
Please use the below as a template when making your report.

## Describe the bug
Crash at USAF Olivia, after clearing the outside, was just walking around about to loot.

### Is it already a known issue?
N/A

### Steps to reproduce
N/A

### Environment
 - OS: Windows
 - RTX 3080
 - 32gb RAM
 - Intel i9-9900k 3.60GHz

   

### Contact: 
    
   Please list your discord name if you are in our discord: spookyboi

LOD seemed to be having issues before this, lots of low res textures. 

[crash-2024-03-10-07-23-24.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14549287/crash-2024-03-10-07-23-24.log)
[Save37_78CE48C2S416E6E61_Commonwealth_000327_20240310072217_11_2.zip](https://github.com/NomadsReach/Fallout-Anomaly/files/14549286/Save37_78CE48C2S416E6E61_Commonwealth_000327_20240310072217_11_2.zip)

**Comment by NomadsReach** [comment]
Plesase update to newest build.
