### ISSUE TITLE
Missing/Bugged Textures USAF Olivia Interior

### ISSUE THREAD

**Issue by Spookyboi34** [NomadsReach/Fallout-Anomaly#59]
Please use the below as a template when making your report.

## Describe the bug
I can see through some walls, and there are textures that pop in and out as you move around. They also seem to flicker a lot. 

### Is it already a known issue?
Nope

### Contact: 
    
   Please list your discord name if you are in our discord: spookyboi

![OLIVIA](https://github.com/NomadsReach/Fallout-Anomaly/assets/22487981/cd692e16-be3f-45ad-b460-2238b54dbbe6)

**Comment by NomadsReach** [comment]
Fixed in upcoming dev build.
