### ISSUE TITLE
Dogmeat as +1 Companion

### ISSUE THREAD

**Issue by Keldargames** [NomadsReach/Fallout-Anomaly#6]
## Summary
Have Dogmeat plus aditional follower

### Basic example
[Include a basic example or links here.](https://www.nexusmods.com/fallout4/mods/13459)
Dogmeat is by design a +1 Companion as it seems. 

### Motivation
Why are we doing this? What use cases does it support? What is the expected outcome?
No real reason to have Dogmeat with you at all because he is inferior to every other companion. With Dogmeat +1 you can have him carry stuff and still have a full companion. Plus he is cute af.

**Comment by NomadsReach** [comment]
0.4.9 Offical will have a feature like this.
