### ISSUE TITLE
Invisible Synths - ArcJet Systems

### ISSUE THREAD

**Issue by Spookyboi34** [NomadsReach/Fallout-Anomaly#60]
Please use the below as a template when making your report.

## Describe the bug
The synths inside ArcJet are invisible, I can only see their floating weapons. I assume this would be the case for all synths in every location, not just ArcJet. 

### Is it already a known issue?
Was reported on the discord, but do not see an issue in the github. 

### Steps to reproduce
Go to ArcJet with Paladin Danse, open the locked door and fight the synths. 

### Environment
Most recent public test build. 

### Contact: 
    
   Please list your discord name if you are in our discord: spookyboi

---

### Additional context
Removing the IW - Synaptic Synth Replacer will make them visible again. I personally don't mind the vanilla synths over the IW ones if they are causing issues. 

---

**Comment by NomadsReach** [comment]
Fixed in upcoming dev build.
