### ISSUE TITLE
crash on start up

### ISSUE THREAD

**Issue by RainingInReverse** [NomadsReach/Fallout-Anomaly#63]
Fallout 4 v1.10.163
Buffout 4 v1.28.6

Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FF765F37BF3 Fallout4.exe+1B27BF3

	[Compatibility]
		F4EE: true
	[Crashlog]
		AutoOpen: true
		PromptUpload: false
	[Fixes]
		ActorIsHostileToActor: true
		CellInit: true
		CreateD3DAndSwapChain: true
		EncounterZoneReset: true
		GreyMovies: true
		MagicEffectApplyEvent: true
		MovementPlanner: true
		PackageAllocateLocation: true
		SafeExit: true
		TESObjectREFRGetEncounterZone: true
		UnalignedLoad: true
		UtilityShader: true
	[Patches]
		Achievements: true
		ArchiveLimit: true
		BSMTAManager: true
		BSPreCulledObjects: true
		BSTextureStreamerLocalHeap: false
		HavokMemorySystem: true
		INISettingCollection: true
		InputSwitch: true
		MaxStdIO: -1
		MemoryManager: false
		MemoryManagerDebug: false
		ScaleformAllocator: true
		SmallBlockAllocator: true
		WorkshopMenu: true
	[Warnings]
		CreateTexture2D: true
		ImageSpaceAdapter: true

SYSTEM SPECS:
	OS: Microsoft Windows 10 Home v10.0.19045
	CPU: GenuineIntel Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	GPU #1: Nvidia GA102 [GeForce RTX 3080 Lite Hash Rate]
	GPU #2: Microsoft Basic Render Driver
	PHYSICAL MEMORY: 12.33 GB/47.92 GB

PROBABLE CALL STACK:
	[ 0] 0x7FF765F37BF3 Fallout4.exe+1B27BF3 -> 491703+0x1F3
	[ 1] 0x7FF765F4386E Fallout4.exe+1B3386E -> 188537+0x3E
	[ 2] 0x7FF765F41E8A Fallout4.exe+1B31E8A -> 345528+0x19A
	[ 3] 0x7FF765F41C48 Fallout4.exe+1B31C48 -> 1237039+0x58
	[ 4] 0x7FF765F3BE66 Fallout4.exe+1B2BE66 -> 1328119+0x36
	[ 5] 0x7FF76514933D Fallout4.exe+0D3933D -> 633524+0x4DD
	[ 6] 0x7FF765146E10 Fallout4.exe+0D36E10 -> 1125396+0xC0
	[ 7] 0x7FF765145950 Fallout4.exe+0D35950 -> 668528+0x20
	[ 8] 0x7FF766D47157 Fallout4.exe+2937157 -> 1104651+0x143
	[ 9] 0x7FFEA5607344 KERNEL32.DLL+0017344
	[10] 0x7FFEA74A26B1    ntdll.dll+00526B1

REGISTERS:
	RAX 0x0                (size_t)
	RCX 0x24BE3688DB0      (void*)
	RDX 0x58C89CFBB8       (void*)
	RBX 0x2                (size_t)
	RSP 0x58C89CF200       (void*)
	RBP 0x58C89CF300       (void*)
	RSI 0x0                (size_t)
	RDI 0x8                (size_t)
	R8  0x3                (size_t)
	R9  0x0                (size_t)
	R10 0x0                (size_t)
	R11 0x7FF765F3A190     (void* -> Fallout4.exe+1B2A190)
	R12 0x1                (size_t)
	R13 0x7FF769EB4890     (void* -> Fallout4.exe+5AA4890)
	R14 0x7FF769EB4880     (void* -> Fallout4.exe+5AA4880)
	R15 0x7FF769EB4780     (void* -> Fallout4.exe+5AA4780)

STACK:
	[RSP+0  ] 0x2                (size_t)
	[RSP+8  ] 0x58C89CFBB8       (void*)
	[RSP+10 ] 0x58C89CF300       (void*)
	[RSP+18 ] 0x24BE3688DB0      (void*)
	[RSP+20 ] 0x58C89CF76D       (void*)
	[RSP+28 ] 0x7FF76721F298     (void* -> Fallout4.exe+2E0F298)
	[RSP+30 ] 0x101              (size_t)
	[RSP+38 ] 0x7FF76721D680     (char*) "0x0001	0x0010
0x0002	0x0040
0x0004	0x0080
0x0008	0x0020
0x0010	0x0008
0x0020	0x00100000
0x0040	0x0002
0x0080	0x0004
0x0100	0x0400
0x0200	0x0800
0x1000	0x4000
0x2000	0x2000
0x4000	0x8000
0x8000	0x1000
0x0009	0x0009
0x000a	0x000a
0x000b	0x000b
0x000c	0x000c
"
	[RSP+40 ] 0x101              (size_t)

**Comment by RainingInReverse** [comment]
> Please upload the actual file. I can't do anything with your comment.

[crash-2024-03-18-18-06-03.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14640797/crash-2024-03-18-18-06-03.log)

**Comment by NomadsReach** [comment]
Please update to the newest version and make an antivirus exception per instructions in the read me.
