### ISSUE TITLE
Perma Crashes after Char Created.

### ISSUE THREAD

**Issue by TimeZzToK1LL** [NomadsReach/Fallout-Anomaly#64]
[crash-2024-03-18-19-05-39.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14641249/crash-2024-03-18-19-05-39.log)

### Steps to reproduce
After Char got created, ill can set my points, and when it normally goes out of the vault the game crashes.

### Environment
 - OS: Windows 11
 - RTX 3080 / 32GB RAM / AMD Ryzen 7800x3d

### Contact: 
    
   Please list your discord name if you are in our discord:
   TimeZzToK1LL

Sorry for Bad English

**Comment by NomadsReach** [comment]
Have you made an exception with your antivirus?

**Comment by NomadsReach** [comment]
[crash-2024-03-18-19-05-39-AUTOSCAN.md](https://github.com/NomadsReach/Fallout-Anomaly/files/14641356/crash-2024-03-18-19-05-39-AUTOSCAN.md)

**Comment by TimeZzToK1LL** [comment]
I got no ant virus, or is Firewall exception what this mean ? ^^

**Comment by NomadsReach** [comment]
![image](https://github.com/NomadsReach/Fallout-Anomaly/assets/144523850/332ecdba-2e82-4c21-ad2d-d3fe35f3de94)


Please make sure you are saying yes to this prompt and not clicking through without reviewing.

**Comment by TimeZzToK1LL** [comment]
![Bild_2024-03-18_203119814](https://github.com/NomadsReach/Fallout-Anomaly/assets/163781041/6d9c6d6c-d019-42b5-a1b6-0437c661e9f6)

**Comment by TimeZzToK1LL** [comment]
[crash-2024-03-18-19-36-48.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14641536/crash-2024-03-18-19-36-48.log)
