### ISSUE TITLE
Crash while fighting Zombies/Ghouls

### ISSUE THREAD

**Issue by Keldargames** [NomadsReach/Fallout-Anomaly#65]
Please use the below as a template when making your report.

## Describe the bug
Shot a Ghoul/Zombie in Super Duper Mart with the Fostech Origin 12 Shotgun ( Random Find, not modified ) while there was a Infestation. Game crashed on hit. Could not replicate as of writing time, will edit if/when i can replicate the crash

### Is it already a known issue?
No

### Steps to reproduce
Not Reproducable as of now

### Environment
 - OS: Win10
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
    
   Please list your discord name if you are in our discord:
Keldar

---

### Additional context
Devteam roxx :) 

---
[crash-2024-03-22-09-07-05.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14720256/crash-2024-03-22-09-07-05.log)

**Comment by NomadsReach** [comment]
Please include your save that was related to that log.

**Comment by Keldargames** [comment]
[saves.zip](https://github.com/NomadsReach/Fallout-Anomaly/files/14731542/saves.zip)
ITs a later save, but the same where the bug happened. Is it possible that SS2 additions are the culprit? I added a few of those for more variance in the settlement building.

**Comment by NomadsReach** [comment]
I am hopeful this has been fixed in the new upcoming dev patch. Please report back under a new report if it happens again.
