### ISSUE TITLE
MCM Categorizer

### ISSUE THREAD

**Issue by Cube-13** [NomadsReach/Fallout-Anomaly#66]
Since there are so many options in the MCM right now, which are also not sorted in any way I can tell hehe, we need to use [MCM Categorizer](https://www.nexusmods.com/fallout4/mods/66311).  You can create Submenus and name them whatever you like, Combat, UI, Companions, etc.  Then drag and drop each MCM entry into a folder and hit Sort By Name to sort things alphabetically.  It will really clean up and organizer the MCM.  It's also made by the guy that makes FallUI so you know it works!

**Comment by NomadsReach** [comment]
It will be added in the final version as it has a known CTD issue which can only be resolved by downloading a fix off of a discord which is against Wabbajack TOS to host.
