### ISSUE TITLE
installation errors

### ISSUE THREAD

**Issue by buffallo1972** [NomadsReach/Fallout-Anomaly#69]
Please use the below as a template when making your report.

### Is it already a known issue?
If so or you are not sure please do not make a new request and see the known issue page. [Here](https://github.com/NomadsReach/Fallout-Anomaly/blob/master/Known%20Issue.md)

### Steps to reproduce
Steps to reproduce the behavior.

### Environment
 - OS: [e.g. Arch Linux]
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
    
   Please list your discord name if you are in our discord:

---

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from discord.

---

**Comment by buffallo1972** [comment]
Hi, I have tried about 5 or 6 times to install this modlist, and I always get the same error:

01:15:02.575 [INFO] (Wabbajack.Installer.StandardInstaller) Found 1058 total files, 1026 matching filesize
01:15:03.157 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Fallout4 - Voices.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\fallout4 - voices.ba2)
01:15:03.157 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCCoast - Voices_en.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\dlccoast - voices_en.ba2)
01:15:03.157 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download enbseries_fallout4_v0496.zip (HTTPDownloader+State|https://build.wabbajack.org/authored_files/direct_link/enbseries_fallout4_v0496.zip_e3e13ed5-ade7-4700-8b76-019bf44d7540)
01:15:03.157 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCNukaWorld - Voices_en.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\dlcnukaworld - voices_en.ba2)
01:15:03.157 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCworkshop03 - Voices_en.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\dlcworkshop03 - voices_en.ba2)
01:15:03.157 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Fallout4_Default.ini (GameFileSourceDownloader+State|Fallout4|1.10.163.0|fallout4_default.ini)
01:15:03.157 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_DLCRobot - Voices_en.ba2 (GameFileSourceDownloader+State|Fallout4|1.10.163.0|data\dlcrobot - voices_en.ba2)
01:15:03.157 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

I've seen on reddit a similar case, from what I understand there must be previous cases, please help!!!

**Comment by Keldargames** [comment]
You have to set the game language to English

**Comment by NomadsReach** [comment]
Thank you @Keldargames :)

**Comment by Semiotikal** [comment]
> BUT DELETE THE ENB FILE AND THE ENB META BEFORE IN DOWNLOADS! 

Sorry I didn't quite understand this, what do you mean here? After installing but before launching the game, delete the enb file in downloads? Before installing delete it in downloads?

**Comment by NeilW2024** [comment]
> You have to set the game language to English. And for the enb that almost always fails to download, you have to manually download the enb file from the website, and place it inside the download folder. BUT DELETE THE ENB FILE AND THE ENB META BEFORE IN DOWNLOADS! Remember to check the known issues thread on discord.

Hi, How do I do those things??
