### ISSUE TITLE
Crash near Diamond city gate infight

### ISSUE THREAD

**Issue by Keldargames** [NomadsReach/Fallout-Anomaly#7]
Please use the below as a template when making your report.

## Describe the bug
Game crashed while fighting some Zombies and a Licker with Fence Sherrifs. Exploding sound, maybe a rocket, then the game crashed

### Is it already a known issue?
Not that i am aware of

### Steps to reproduce
As of now, could not be replicated in the same cell

### Environment
 - OS: WIn10
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
    
   Please list your discord name if you are in our discord:
Keldar

---

### Additional context
Crashlog below

---
[crash-2024-02-15-11-14-42.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14296015/crash-2024-02-15-11-14-42.log)

**Comment by NomadsReach** [comment]
Usually due to a number of events going on at the same time and overloads engine. Hope to increase performance with new patches soon. :)
