### ISSUE TITLE
Crash near Diamond City

### ISSUE THREAD

**Issue by Keldargames** [NomadsReach/Fallout-Anomaly#73]
Please use the below as a template when making your report.

## Describe the bug
Game Crashes when near Diamond City while FEN Sheriffs fight Super mutants near Hangmans Alley

### Is it already a known issue?
No

### Steps to reproduce
TPing to diamondcity and runnin towards the fight reproduces the Crash

### Environment
 - OS:Win10 [e.g. Arch Linux]
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
    Keldar
   Please list your discord name if you are in our discord:

---

### Additional context
Updated to the DEV Branch correctly this time. I have some SS2 Addons and Place everywhere added to the Modpack, but have not Sorted them, so they are last in the load order. Just in Case the Crash is tied to those added mods or wrong load order. Added Crashlog and Save for reference

---
[crash-2024-03-24-13-12-04.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14735556/crash-2024-03-24-13-12-04.log)
[crash-2024-03-24-13-17-50.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14735557/crash-2024-03-24-13-17-50.log)

[saves.zip](https://github.com/NomadsReach/Fallout-Anomaly/files/14735560/saves.zip)

**Comment by NomadsReach** [comment]
Besides like the 50 different SS2 plot mods (lol) this area is notorious for crashing due to just overloading the engine. If it happens on a consistent basis please open a new report.

**Comment by NomadsReach** [comment]
Also, place everywhere was confirmed to be causing issues in previous build.
