### ISSUE TITLE
Texture Flickering in Diamond city

### ISSUE THREAD

**Issue by Keldargames** [NomadsReach/Fallout-Anomaly#74]
Please use the below as a template when making your report.

## Describe the bug
Texture flickering in Diamond City

### Is it already a known issue?
Was/is known. Part should be patched in the dev build. in case this is new i open a bug report

### Steps to reproduce
Everytime i enter Diamond City

### Environment
 - OS:Win10 [e.g. Arch Linux]
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
    
   Please list your discord name if you are in our discord:

Keldar
---

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from discord.
https://youtu.be/pJnpZ3AI-4Y
---

**Comment by NomadsReach** [comment]
This is fixed in the new dev update that is released on the nexus.
