### ISSUE TITLE
Random? Crash while at settlement workbench

### ISSUE THREAD

**Issue by Keldargames** [NomadsReach/Fallout-Anomaly#77]
Please use the below as a template when making your report.

## Describe the bug
Game crashes while storing stuff at the Settlement workbench. 

### Is it already a known issue?
Nope

### Steps to reproduce
Seems to happen everytime i am at the workbench in Red Rocket
### Environment
 - OS:Win10 [e.g. Arch Linux]
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
  
   Please list your discord name if you are in our discord: Keldar

---

### Additional context
May be related to Fens stuff. I wanted to store Happy Meal, Noodles and stuff and i think it always happen while trying to store that stuff. Also i enhanced the Modpack with SS2 Addons and Place Everywhere, just in case
EDIT:
Not related to storing stuff. Being around Red Rocket seem to crash after about 10 minutes.
---
[saves.zip](https://github.com/NomadsReach/Fallout-Anomaly/files/14754596/saves.zip)
[crash-2024-03-26-07-49-02.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14754611/crash-2024-03-26-07-49-02.log)
[crash-2024-03-26-07-52-27.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14754612/crash-2024-03-26-07-52-27.log)

**Comment by NomadsReach** [comment]
I have not been able to produce your issue, and your crash log was related to a navmesh issue. Please open a new ticket if the issue happens again.
