### ISSUE TITLE
Crashing on startup

### ISSUE THREAD

**Issue by GarryNards** [NomadsReach/Fallout-Anomaly#80]
## Describe the bug
Whenever I launch the game I get a black screen with ENB watermark it loads for a moment and then crashes. I've tried on Dev and public builds 

### Is it already a known issue?
Does not look like it

### Steps to reproduce
Launching the game

### Environment
 - OS: Windows 11 
 - Hardware
RTX 3080
i7 9700k 
16GB RAM (With Page file)
Installed on NVME

### Contact: 
    Discord: garrynards
[crash-2024-04-04-23-56-28.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14878292/crash-2024-04-04-23-56-28.log)

**Comment by NomadsReach** [comment]
[crash-2024-04-04-23-56-28-AUTOSCAN.md](https://github.com/NomadsReach/Fallout-Anomaly/files/14900083/crash-2024-04-04-23-56-28-AUTOSCAN.md)

**Comment by NomadsReach** [comment]
Have you modded the list at all or moved any mods around?
