### ISSUE TITLE
Custom faces are just horrific, how to remove?

### ISSUE THREAD

**Issue by Semiotikal** [NomadsReach/Fallout-Anomaly#81]
Hey there, love the mod, it basically hits all the gaps I found in Lost World and other similar FO mods.

Only gripe is that the custom faces that were added for characters like Garvey and Sturgis and such are just horrific looking. They look like talking mannequins. 

What mod in the list did the replacement (so I can turn it off in MO2) and is it possible to turn off in a save game? 

Thanks again 👍

edit: just want to specify its mainly the companion characters who's faces are just not good. Other NPCs are fine but Its not super important to me either way so if I cant just remove the companion faces then I'll remove them all.

**Comment by NomadsReach** [comment]
This is an issue I am aware of, and I plan on doing a full rework of all faces once the list is out of it's final beta stages in a few more updates.

**Comment by NomadsReach** [comment]
Beta version of NPC update coming this weekend. :)
