### ISSUE TITLE
error that does not make the game start

### ISSUE THREAD

**Issue by therealSonbull** [NomadsReach/Fallout-Anomaly#82]
Please use the below as a template when making your report.

after starting MO2, i try to run the game (Fall Out 4 : Anomaly) but i get an error message that says: TypeError:'NoneType' object not iterable
at:
wabbajack/plugins\rootbuilder\plugin\rootbuilder\modules\rootbuilder_data.py(32):loadDataFile
wabbajack/plugins\rootbuilder\plugin\rootbuilder\core\rootbuilder.py(72):build
wabbajack/plugins\rootbuilder\plugin\rootbuilder\plugins\rootbuilder_autobuild.py(62):onAboutToRun
wabbajack/plugins\rootbuilder\plugin\rootbuilder\plugins\rootbuilder_autobuild.py(14):<lambda>.

### Is it already a known issue?
If so or you are not sure please do not make a new request and see the known issue page. [Here](https://github.com/NomadsReach/Fallout-Anomaly/blob/master/Known%20Issue.md)

### Steps to reproduce
don't know just happened after starting SS2 in the mod pack and then logging off the game, when i wanted to restart the game got the message

### Environment
 - OS: [e.g. Arch Linux]
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
    
Sonbull
<img width="378" alt="FO error" src="https://github.com/NomadsReach/Fallout-Anomaly/assets/166961872/5cf6a0d0-85ee-4895-a57c-7ace6921638a">

---

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from discord.

---

**Comment by NomadsReach** [comment]
You are missing required files that are covered in the read me or your antivirus is removing files. Update to the newest build and join the discord!
