### ISSUE TITLE
Install fail - how to correct? Plz help!

### ISSUE THREAD

**Issue by NeilW2024** [NomadsReach/Fallout-Anomaly#83]
Hi

The install fails with the last file - an enb. I appreciate its been logged before but for us noobs a little help would be much appreciated!

00:00:33.638 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download enbseries_fallout4_v0496.zip (HTTPDownloader+State|https://build.wabbajack.org/authored_files/direct_link/enbseries_fallout4_v0496.zip_e3e13ed5-ade7-4700-8b76-019bf44d7540)
00:00:33.638 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

1. How do I download that file?
2. How do I get the install to proceed?

Best wishes 

Neil

**Comment by Artem-Chet** [comment]
The link is no longer valid it seems
I was able to work around this by downloading the same file but with a new link from wabbajack.org. I then placed it in the downloads folder and restarted the install and it picked it up.

https://build.wabbajack.org/authored_files/direct_link/enbseries_fallout4_v0496.zip_77d37de8-93d8-4871-8683-18896a8d3b68

And in case that link also expires. You can search for it on the following page https://build.wabbajack.org/authored_files

**Comment by NeilW2024** [comment]
HiThank you - worked on the first link!Much appreciated Neil Neil Walshaw07791 795228On 14 Apr 2024, at 06:30, Artem Chetverikov ***@***.***> wrote:﻿
The link is no longer valid it seems
I was able to work around this by downloading the same file but with a new link from wabbajack.org. I then placed it in the downloads folder and restarted the install and it picked it up.
https://build.wabbajack.org/authored_files/direct_link/enbseries_fallout4_v0496.zip_77d37de8-93d8-4871-8683-18896a8d3b68
And in case that link also expires. You can search for it on the following page https://build.wabbajack.org/authored_files

**Comment by NomadsReach** [comment]
Hello, this issue has been covered in much detail in the discord and is not an issue with the newest update. Please join the discord!!
