### ISSUE TITLE
Game crashes on RUN start up

### ISSUE THREAD

**Issue by PinkPengy** [NomadsReach/Fallout-Anomaly#84]
[crash-2024-04-14-11-50-15.log](https://github.com/NomadsReach/Fallout-Anomaly/files/14970694/crash-2024-04-14-11-50-15.log)

**Comment by NomadsReach** [comment]
More than likely due to running overlays or missing a step in the read me.

**Comment by NomadsReach** [comment]
Confirm you have gone through the read me and join our discord for more support.
