### ISSUE TITLE
No way to "Disable Forced Refresh" MCM Prompt 

### ISSUE THREAD

**Issue by beryllium22** [NomadsReach/Fallout-Anomaly#85]
There is a prompt that is constantly spammed 
![image](https://github.com/NomadsReach/Fallout-Anomaly/assets/97590627/0fb0f93d-7faf-492e-89e8-76eb118efe77)
Neither GPT nor Google knows what im talking about. A search through the folders of all MCM related mods yielded nothing for a fix. Checking ever MCM related settings menu also yielded no results. So ive gotta assume this is either a problem with the pack or perhaps wabbajack?

I7 13700k
64gb DDR4 3600mhz @16cl
RTX 4070
(Latest Build of the pack)

**Comment by NomadsReach** [comment]
Update to the newest build, and to save yourself problems join the discord.
