### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by TrustyTraitor** [NomadsReach/Fallout-Anomaly#86]
## Describe the bug
When I attempt to launch the game it immediately crashes and opens the attached crashlog
[crash-2024-04-17-01-56-43.log](https://github.com/NomadsReach/Fallout-Anomaly/files/15004582/crash-2024-04-17-01-56-43.log)

### Steps to reproduce
Launch game after clean install

### Environment
 - OS: Windows 11
 - Hardware: i5-13600kf, RTX 4080, 32gb ddr5
 - Not on an admin account
 - I have setup the page file. 
 - All overlays are disabled
 - I do not have the game (nor modlist) installed on a protected drive or folder. 

   
### Contact: 
    
 Discord:
  trustytraitor

**Comment by TrustyTraitor** [comment]
I also made sure that windows defender had exceptions for all files/folders listed in the readme

**Comment by KRANKENHAUS2112** [comment]
Please install https://github.com/abbodi1406/vcredist/releases/download/v0.78.0/VisualCppRedist_AIO_x86_x64.exe . I had the same exact issue.

**Comment by NomadsReach** [comment]
Has your issue been resolved, @TrustyTraitor

**Comment by NomadsReach** [comment]
This issue has been fixed. 
![image](https://github.com/NomadsReach/Fallout-Anomaly/assets/144523850/f9734931-8416-4fb9-ae0c-a64116fcaf15)
https://github.com/NomadsReach/Fallout-Anomaly/issues/92

**Comment by NomadsReach** [comment]
Please see issue: https://github.com/NomadsReach/Fallout-Anomaly/issues/92 for the temp fix.
