### ISSUE TITLE
Crash after after character creation 

### ISSUE THREAD

**Issue by mrbl0o0** [NomadsReach/Fallout-Anomaly#87]
Please use the below as a template when making your report.

## Describe the bug
Crashes after doing my stats and adding my name. After I press "accept" the game would load than crash mid loading. 

### Steps to reproduce
1. start a new game
2. finish character creations 
3. finish stats and naming 
4. press "accept"
5. let the game load than it crashes mid loading 

### Environment
 - OS: Windows 10
 - Hardware
 - intel 15-13600kf, 3500 Mhz, 14 core 
 - 32 GB Ram 
 - GTX 3060 Ti 
 - don't have any anti virus beside the window defender 
 - 
 Crash Log 

[crash-2024-04-18-01-44-31.log](https://github.com/NomadsReach/Fallout-Anomaly/files/15018893/crash-2024-04-18-01-44-31.log)

### Contact: 
    
   Mrbloo 

---

### Additional context

---

**Comment by bravestduck23** [comment]
Turn off active virus protection in defender, worked for me

**Comment by NomadsReach** [comment]
[crash-2024-04-18-01-44-31 (1)-AUTOSCAN.md](https://github.com/NomadsReach/Fallout-Anomaly/files/15043987/crash-2024-04-18-01-44-31.1.-AUTOSCAN.md)

- (void* -> gameoverlayrenderer64.dll+009B7E3) | 1
- (void* -> gameoverlayrenderer64.dll+00AA58E) | 1
- (void* -> gameoverlayrenderer64.dll+00B1577) | 1
- (void* -> gameoverlayrenderer64.dll+00B528C) | 1

**Comment by NomadsReach** [comment]
Make an excetion in your antivrisus and disable all overlays.
