### ISSUE TITLE
crash file attatched

### ISSUE THREAD

**Issue by AggravatedSpoon** [NomadsReach/Fallout-Anomaly#89]
[crash-2024-04-18-21-43-24.log](https://github.com/NomadsReach/Fallout-Anomaly/files/15030877/crash-2024-04-18-21-43-24.log)

**Comment by NomadsReach** [comment]
[crash-2024-04-18-21-43-24-AUTOSCAN.md](https://github.com/NomadsReach/Fallout-Anomaly/files/15043964/crash-2024-04-18-21-43-24-AUTOSCAN.md)

**Comment by NomadsReach** [comment]
# Checking for *[HUD / Interface Crash]...... SUSPECT FOUND! > Severity : 1 # 

Have you changed anything in the list?

**Comment by AggravatedSpoon** [comment]
> # Checking for *[HUD / Interface Crash]...... SUSPECT FOUND! > Severity : 1
> Have you changed anything in the list?

No
