### ISSUE TITLE
Movement issue

### ISSUE THREAD

**Issue by JustBaron1** [NomadsReach/Fallout-Anomaly#9]
Please use the below as a template when making your report.

## Describe the bug
Moving in the opposite direction from a third person

### Is it already a known issue?
No

### Steps to reproduce
Pressing "S" then "D" with gun out in 3rd person results in wrong direction of movement (Not simultaneously, but sequentially). Instead of back+right, character goes forward+left.

### Environment
 - OS: Windows 11
 - Hardware
 - Other details that you think may affect.
   

### Contact: 
    just_baron

---

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from discord.

---

**Comment by NomadsReach** [comment]
Please confirm which weapon this is. This is an issue when a weapon mod does not have the proper animation files provided upon download.

**Comment by JustBaron1** [comment]
It was a default AKM from NPC's corpse. 

Also, remembered another bug, but some of AK spawn without attachments. For example, there was one without barrel that still could shoot.

**Comment by NomadsReach** [comment]
Thank you, this should now be fixed in upcoming patch.
