### ISSUE TITLE
Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FF61AF225DB Fallout4.exe+21525DB

### ISSUE THREAD

**Issue by Vanakka** [NomadsReach/Fallout-Anomaly#90]
[crash-2024-04-19-00-25-57.log](https://github.com/NomadsReach/Fallout-Anomaly/files/15031815/crash-2024-04-19-00-25-57.log)
Please use the below as a template when making your report.

## Describe the bug
Game Crash

### Is it already a known issue?
If so or you are not sure please do not make a new request and see the known issue page. [Here](https://github.com/NomadsReach/Fallout-Anomaly/blob/master/Known%20Issue.md)

### Steps to reproduce
Steps to reproduce the behavior.
playing normally

### Environment
 - OS: Microsoft Windows 11 Home v10.0.22631
 - Hardware
	CPU: AuthenticAMD AMD Ryzen 7 7800X3D 8-Core Processor           
	GPU #1: Nvidia AD103 [GeForce RTX 4080]
	GPU #2: Microsoft Basic Render Driver
	PHYSICAL MEMORY: 15.66 GB/31.18 GB
 - Other details that you think may affect.
   

### Contact: 
    
   Please list your discord name if you are in our discord:
@Vanakka

---

### Additional context
Add any other context about the problem here or screenshots/videos/ticket transcript from discord.

---

**Comment by NomadsReach** [comment]
Are you running any overlays and have you updated to the new build by clicking on overwrite install when you did?

**Comment by NomadsReach** [comment]
https://github.com/abbodi1406/vcredist/releases/download/v0.78.0/VisualCppRedist_AIO_x86_x64.exe

Run this as well.

**Comment by NomadsReach** [comment]
Please see issue: https://github.com/NomadsReach/Fallout-Anomaly/issues/92 for the possible temp fix at this time.
