### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by jimbob907** [NomadsReach/Fallout-Anomaly#92]
Please use the below as a template when making your report.

## Describe the bug
the game barely ever launches from the mod organizer and when it does i instantly get a crash report on the main menu

### Steps to reproduce
just trying to launch the game

### Environment
 - OS: windows
 - AMD Ryzen 7 5700X 8-Core Processor    
 -  RAM 32.0 GB
 - GPU nivdia 3080

 
   

---

### Additional context
I've gone through the read me twice and have done everything

---

**Comment by NomadsReach** [comment]
Have you updated to the newest build?


If so....there seems to be an issue with The Laser Garand - a Post War Battle Rifle. Please disable that mod for the time being, and install this mod into mo2 and make sure to enable on the mod side and the plugin side.

**Comment by NomadsReach** [comment]
https://filebin.net/33ufpunyhz2h7tu1/Fallout_Anomaly_Master_Conflict_Stomper.7z

**Comment by NomadsReach** [comment]
Please download the mod from the link above. This is all being tested atm so please report back if you are good.
