### ISSUE TITLE
LOW FPS 

### ISSUE THREAD

**Issue by jimbob907** [NomadsReach/Fallout-Anomaly#96]
Please use the below as a template when making your report.

## Describe the bug
just running low fps and trying to figure out a way to fix it

### Environment
OS: windows
AMD Ryzen 7 5700X 8-Core Processor
RAM 32.0 GB
GPU nivdia 3080
   

---

---

**Comment by NomadsReach** [comment]
ISSUE BEING TRACKED HERE: https://sharing.clickup.com/9014300118/b/h/6-901402934880-2/cc0f0180c0708ba
