### ISSUE TITLE
Disk Cache Causing Long Loading

### ISSUE THREAD

**Issue by coc568** [NomadsReach/Fallout-Anomaly#98]
https://www.nexusmods.com/fallout4/mods/74841?tab=posts

REPORTS: 

![Image](https://github.com/user-attachments/assets/bcad8c15-2da0-4168-8686-b64f9043afbc)

![Image](https://github.com/user-attachments/assets/6f1eea64-3568-4a34-ad67-6ac6fb1c5a7c)

**Comment by NomadsReach** [comment]
![image](https://github.com/user-attachments/assets/de8695ae-62d6-4877-bce9-5e41199d3842)

https://www.nexusmods.com/fallout4/mods/84214

Will be removed and replaced with XCELL in next update.
